# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63a5ab4250dbf455782ed5a3aed1e55a775d0cad91f157b52d913e14a6cff9a13a3301ca10b16c36a37f597e962102f98317f81b12fe6542e35d5c0e5d6755b5

test:
  secret_key_base: f88686c974e965653c4b24deeb37d2c8ed8b3e6e3e934d6a9237fd7cf7008ed78ffb6b96980f6ad7e047dbc6a3c3f842831fff3d0e56a083aef60b28667435b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
